-- Custom Types
create type public.card_status as enum ('hidden', 'open');

-- Create tables
create table public.rooms (
  id uuid default gen_random_uuid() not null primary key,
  name varchar not null,
  card_status card_status default 'hidden'::public.card_status not null,
  cards int4[] default '{1, 2, 3, 5, 8, 13, 21}' not null,
  players json default '[]' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index on public.rooms (updated_at);

create table public.room_users (
  id bigint generated by default as identity primary key,
  room_id uuid references public.rooms not null,
  user_id uuid references auth.users not null
);
create unique index on public.room_users (room_id, user_id);

-- Extensions and triggers
create extension if not exists moddatetime schema extensions;

create trigger handle_room_updated_at before update on public.rooms
  for each row execute procedure moddatetime (updated_at);

-- Secure the tables
alter table public.rooms enable row level security;

create policy "Allow select access" on public.rooms
  for select to authenticated using (
    auth.uid() in (
      select user_id from room_users
      where room_id = rooms.id
    )
  );

create policy "Allow update access" on public.rooms
  for update to authenticated using (
    auth.uid() in (
      select user_id from room_users
      where room_id = rooms.id
    )
  );

create policy "Allow delete access" on public.rooms
  for delete to authenticated using (
    auth.uid() in (
      select user_id from room_users
      where room_id = rooms.id
    )
  );


-- Only allow realtime listening on public tables.
drop publication if exists supabase_realtime;
create publication supabase_realtime for table rooms;
