-- Create tables
create table public.requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  content varchar(4000) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
